version: "3.8"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://milvus-etcd:2379
    ports:
      - "2379:2379"

  milvus:
    image: milvusdb/milvus:v2.4.0
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    container_name: milvus
    environment:
      ETCD_ENDPOINTS: milvus-etcd:2379
      STORAGE_TYPE: local
      MINIO_ADDRESS: "milvus-minio:9000"
    volumes:
      - ./milvus_data:/var/lib/milvus
      - ./milvus_logs:/milvus/logs
    shm_size: "2gb"
    deploy:
      resources:
        limits:
          memory: 6g
    depends_on:
      - etcd
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio
    container_name: milvus-minio
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data

  code-context-mcp:
    build:
      context: ./code-context-mcp
    ports:
      - "4444:4444"
    environment:
      MILVUS_ADDRESS: "milvus:19530"
      EMBEDDING_PROVIDER: Ollama
      EMBEDDING_MODEL: nomic-embed-text
      OLLAMA_MODEL: llama3
      OLLAMA_HOST: "http://ollama:11434"
    container_name: code-context-mcp
    volumes:
      - ./mcp_logs:/app/logs
      - ./mcp_data:/app/data
    depends_on:
      milvus:
        condition: service_healthy
      ollama:
        condition: service_healthy

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "\
      ollama serve & \
      sleep 2 && \
      ollama pull nomic-embed-text && \
      wait"]
    healthcheck:
      test: ["CMD-SHELL", "ollama list | grep -q nomic-embed-text"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s
volumes:
  ollama-data:
