version: "3.8"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      ETCD_AUTO_COMPACTION_MODE: revision
      ETCD_AUTO_COMPACTION_RETENTION: "1000"
      ETCD_QUOTA_BACKEND_BYTES: "4294967296"
      ETCD_SNAPSHOT_COUNT: "50000"
      ETCD_ENABLE_V2: "false"
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://milvus-etcd:2379
    ports:
      - "2379:2379"

  milvus:
    image: milvusdb/milvus:v2.4.0
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    container_name: milvus
    environment:
      MILVUS_LOG_LEVEL: debug
      ETCD_ENDPOINTS: milvus-etcd:2379
      STORAGE_TYPE: local
      MINIO_ADDRESS: "milvus-minio:9000"
    volumes:
      - ./milvus_data:/var/lib/milvus
      - ./milvus_logs:/milvus/logs
    shm_size: "2gb"
    deploy:
      resources:
        limits:
          memory: 6g
    depends_on:
      - etcd
      - minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio
    container_name: milvus-minio
    command: server /data --console-address ":9001"
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data

  code-context-mcp:
    build:
      context: ./code-context-mcp
    ports:
      - "4444:4444"
    environment:
      MILVUS_ADDRESS: "milvus:19530"
      EMBEDDING_PROVIDER: ${EMBEDDING_PROVIDER}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    container_name: code-context-mcp
    depends_on:
      milvus:
        condition: service_healthy
